name: Docker test
on:
  push:
    branches: [ "feature/docker-web-hub" ]
  pull_request:
    branches: [ "feature/docker-web-hub" ]
jobs:
  run-test:
    environment: DOCKER
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: log in docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
