name: Docker test
on:
  push:
    branches: [ "helm/test-repo-chart" ]
  pull_request:
    branches: [ "helm/test-repo-chart" ]
jobs:
  run-test:
    environment: DOCKER
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: log in docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: build candles
        run: docker build -f Dockerfile.app -t candles .
      - name: build candle_nginx
        run: docker build -f Dockerfile.web -t candle_nginx .
      - name: container compose
        run: docker compose up --build --abort-on-container-exit
      - name: tag n push app
        run: |
          docker tag candles ${{secrets.DOCKER_USERNAME}}/test-repo-app
          docker push ${{secrets.DOCKER_USERNAME}}/test-repo-app
      - name: tag n push web
        run: |
          docker tag candle_nginx ${{secrets.DOCKER_USERNAME}}/test-repo-web
          docker push ${{secrets.DOCKER_USERNAME}}/test-repo-web
      - name: get helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.17.3'

      - name: tag version check
        id: get-version
        run: |
          VERSION=$(test-repo-chart/Chart.yaml)
          echo "${VERSION}" >> $GITHUB_OUTPUT

      
        
      
